TUNING = GLOBAL.TUNING

local seg_time = 30
local total_day_time = seg_time*16

--clockwork tower
TUNING.CLOCKWORK_TOWER_REVEAL_RANGE = GetModConfigData("clockwork_tower_reveal_range")
TUNING.CLOCKWORK_TOWER_POUND_COOLDOWN = 3.5 
TUNING.CLOCKWORK_TOWER_HEALTH = 2000
TUNING.CLOCKWORK_TOWER_DAMAGE = 45
TUNING.CLOCKWORK_TOWER_TARGET_DIST = 12
TUNING.CLOCKWORK_TOWER_MAX_CHASEAWAY_DIST = 40*40
TUNING.CLOCKWORK_TOWER_EXPLODE_COOLDOWN = 20

--gardenslug
TUNING.GARDENSLUG_HEALTH = 1500
TUNING.GARDENSLUG_DROP_TIME = (GetModConfigData("gardenslug_drop_time") - 1)*total_day_time
TUNING.GARDENSLUG_DROP_TIME_VARIANCE = total_day_time*2
TUNING.GARDENSLUG_SPAWNEGG_COOLDOWN = 20
TUNING.GARDENSLUG_MAX_SLUGLINGS = 5

--slugling 
TUNING.SLUGLING_HEALTH = 250
TUNING.SLUGLING_DAMAGE = 30
TUNING.SLUGLING_ATTACK_PERIOD = 3
TUNING.SLUGLING_TARGET_DIST = 4

--insect meat
TUNING.INSECT_MEAT_RAW_CALORIES = 25
TUNING.INSECT_MEAT_COOKED_CALORIES = 40
TUNING.INSECT_MEAT_DRIED_CALORIES = 30
TUNING.INSECT_MEAT_RAW_HEALING = -10
TUNING.INSECT_MEAT_COOKED_HEALING = 20
TUNING.INSECT_MEAT_DRIED_HEALING = 25
TUNING.INSECT_MEAT_RAW_SANITY = -40
TUNING.INSECT_MEAT_COOKED_SANITY = 0
TUNING.INSECT_MEAT_DRIED_SANITY = 5

--jaid plant
TUNING.JAID_PLANT_REGROW_TIME = total_day_time*5

--plantaid
TUNING.PLANTAID_HEALING = 12
TUNING.PLANTAID_PERISH_TIME = total_day_time 
TUNING.PLANTAID_DRY_TIME = total_day_time

TUNING.STERILIZED_PLANTAID_HEALING = 10

--flintchick 
TUNING.FLINTCHICKHERD_MAX_SIZE = 4
TUNING.FLINTCHICK_BABYDELAY = (GetModConfigData("flintchick_respawn_time"))*total_day_time
TUNING.FLINTCHICK_BABYDELAY_VARIANCE = 0.5*total_day_time

--beebeetle 
TUNING.BEEBEETLE_HEALTH = 600
TUNING.BEEBEETLE_DAMAGE = 50
TUNING.KILLERBEEBEETLE_HEALTH = 700
TUNING.KILLERBEEBEETLE_DAMAGE = 60
TUNING.BEEBEETLE_ATTACK_PERIOD = 4.5
TUNING.BEEBEETLE_ATTACK_RANGE = 2.5
TUNING.BEEBEETLE_SPEED = 1.75
TUNING.BEEBEETLE_SPEED_FAST = 3.25
TUNING.BEEBEETLE_SPEED_WATER = 2.5
TUNING.BEEBEETLE_SPEED_WATER_FAST = 4.5

--beebeetle den
TUNING.BEEBEETLEDEN_MINE = 12
TUNING.BEEBEETLEDEN_RELEASE_TIME = total_day_time / 3
TUNING.BEEBEETLEDEN_REGEN_TIME = total_day_time
TUNING.BEEBEETLEDEN_MAX_BEES = 3
TUNING.BEEBEETLEDEN_HARVEST_TIME = total_day_time * 5