if not GLOBAL.STRINGS.CHARACTERS.WIRLYWINGS then 
    return 
end 

local WIRLYWINGSDESCRIBE = GLOBAL.STRINGS.CHARACTERS.WIRLYWINGS.DESCRIBE

local CHARACTERDESCRIBE = {
    WIRLYWINGSDESCRIBE, 
}

WIRLYWINGSDESCRIBE.CLOCKWORK_TOWER = ""
WIRLYWINGSDESCRIBE.JAID_PLANT_PLANT = "" 
WIRLYWINGSDESCRIBE.PLANTAID = "" 
WIRLYWINGSDESCRIBE.STERILIZED_PLANTAID = "" 
WIRLYWINGSDESCRIBE.INSECT_MEAT_RAW = ""  -- insect meat foods: hated
WIRLYWINGSDESCRIBE.INSECT_MEAT_COOKED = "" 
WIRLYWINGSDESCRIBE.INSECT_MEAT_DRIED = "" 
WIRLYWINGSDESCRIBE.CROAKUEMBOUCHE = "" 
WIRLYWINGSDESCRIBE.NUTRIENTPASTE = "" 
WIRLYWINGSDESCRIBE.GARDENSLUG = "" 
WIRLYWINGSDESCRIBE.SLUGLING = "" 
WIRLYWINGSDESCRIBE.FLINTCHICK = "" 
WIRLYWINGSDESCRIBE.BEEBEETLE = "" 
WIRLYWINGSDESCRIBE.KILLERBEEBEETLE = "" 
WIRLYWINGSDESCRIBE.BEEBEETLEDEN = "" 
WIRLYWINGSDESCRIBE.BEEBEETLEBOULDER = "" 

for _, CHARACTER in pairs(CHARACTERDESCRIBE) do 
    CHARACTER.JAID_PLANT_ROOT = CHARACTER.JAID_PLANT_PLANT

    CHARACTER.STONECHICK = CHARACTER.FLINTCHICK
    CHARACTER.REDGOLDCHICK = CHARACTER.FLINTCHICK
    CHARACTER.BLUEGOLDCHICK = CHARACTER.FLINTCHICK

    CHARACTER.FLOATY_FLINT = CHARACTER.FLINT
    CHARACTER.FLOATY_ROCKS = CHARACTER.ROCKS 
    CHARACTER.FLOATY_NITRE = CHARACTER.NITRE 
    CHARACTER.FLOATY_GOLDNUGGET = CHARACTER.GOLDNUGGET

    CHARACTER.HIBEEBEETLE = CHARACTER.BEEBEETLE
    CHARACTER.HIBEEBEETLEBOULDER = CHARACTER.BEEBEETLEBOULDER
end 